backend:
  name: github
  branch: master
  repo: buhrmi/sveltekit-netlify-cms
collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - name: title
      - name: body
media_folder: "static/netlify"
public_folder: "/netlify"

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg