backend:
  name: git-gateway
  branch: master
collections:
  - name: pages
    folder: _netlify/pages
    create: true
    fields:
      - name: title
      - name: body
media_folder: "static/images/netlify"
public_folder: "/images/netlify"

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg